FactoryGirl.define do
  # we define our factory for the Campaign model in has_secure_password
  # remember that this should always succeed in giving a valid campaign
  factory :campaign do
    # every object generated by the factory would be static
    # title is a method
    # need {} to generate new instance each time FactoryGirl.build is called
    # using a sequence will guarantee each dynamic generation will be unique
    # title {Faker::Company.bs}
    # sequence is a method from factory girl
    sequence(:title) {|n| "#{Faker::Company.bs}-#{n}" }
    body             { Faker::Hipster.paragraph       }
    goal             { 11 + rand(100000)              }
    end_date         { Time.now + rand(120).days      }
  end


end
